tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "mistertea/et"
brew "xz"
brew "git"
brew "htop"
brew "imagemagick"
brew "lftp"
brew "zstd"
brew "mas"
brew "media-info"
brew "mtr"
brew "pigz"
brew "pixz"
brew "pv"
brew "rclone"
brew "terraform"
brew "tmate"
brew "tmux"
brew "topgrade"
brew "unrar"
brew "watch"
brew "wget"
brew "youtube-dl"
brew "zsh"
brew "zsh-completions"
brew "mistertea/et/et"
cask "1password-beta"
cask "1password-cli"
cask "alfred"
cask "appcleaner"
cask "cheatsheet"
cask "clean-me"
cask "daisydisk"
cask "discord"
cask "docker"
cask "dozer"
cask "firefox"
cask "font-jetbrains-mono"
cask "iina"
cask "imageoptim"
cask "impactor"
cask "istat-menus"
cask "iterm2-beta"
cask "monitorcontrol"
cask "moom"
cask "multi"
cask "notion"
cask "scroll-reverser"
cask "shadow"
cask "slack"
cask "sublime-text-dev"
cask "tower"
cask "transmit"
cask "visual-studio-code"
cask "zoomus"
mas "Lieferungen", id: 290986013
mas "NextDNS", id: 1464122853
mas "Pixelmator", id: 407963104
mas "Theine", id: 955848755
mas "Mela" 1548466041
mas "Default Browser" 1055264211
mas "Theine" 955848755
mas "PopClip" 445189367
mas "Home Assistant" 1099568401
