---
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - carthage
    - cmake
    - ctags
    - curl
    - git
    - go
    - hub
    - htop-osx
    - httpie
    - mtr
    - node
    - openssl
    - pv
    - the_silver_searcher
    - thefuck
    - tmux
    - tree
    - vim
    - youtube-dl
    - zsh

- name: Install Homebrew Cask apps
  homebrew_cask: name={{ item }} state=present
  with_items:
    - seil
    - iterm2
    - keepingyouawake
    - slack
    - sequel-pro
    - flux

- name: Cleanup Brew packages
  command: brew cleanup

